{{- if .Values.httproute.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "evcc.fullname" . }}
  labels:
    {{- include "evcc.labels" . | nindent 4 }}
  {{- with .Values.httproute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  hostnames:
    {{- range .Values.httproute.hostnames }}
    - {{ . | quote }}
    {{- end }}
  parentRefs:
    - name: {{ .Values.httproute.parentRef.name }}
      namespace: {{ .Values.httproute.parentRef.namespace }}
      sectionName: {{ .Values.httproute.parentRef.sectionName }}
  rules:  {{- .Values.httproute.rules | toYaml | nindent 2 }}
    backendRefs:
    - name: {{ include "evcc.fullname" $ }}
      port: {{ .Values.service.port }}
{{- end }}