name: Release Chart

on:
  push:
    branches:
      - main

jobs:

  release:
  
    permissions:
      contents: write

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run helm-docs
        uses: losisin/helm-docs-github-action@v1
        with:
          input: values.yaml
          git-push: true
          git-push-user-name: "Helm Docs Bot"
          git-push-user-email: "helm-docs-bot@users.noreply.github.com"
          git-commit-message: "chore: update Helm documentation"

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_TOKEN: "${{ secrets.RELEASE_TOKEN }}"